# Site settings
title: Sean Martin Maguire
email: smmaguire@utexas.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://smmaguire.github.io" # the base hostname & protocol for your site
twitter_username: sm_maguire
github_username:  smmaguire
name: Sean Maguire
email_full: mailto:smmaguire@gmail.com
website: smmaguire.github.io
website_full: https://smmaguire.github.io
github: smmaguire
twitter: sm_maguire
tel: 4134332918
tel_full: tel:4134332918
google_maps: ''
address: 314 West 34th Street
postcode: 78705
city: Austin, TX
country: USA
# Build settings
markdown: kramdown
