# Site settings
title: Sean Martin Maguire
email: smmaguire@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site
baseurl: "/smmaguire.github.io/" # the subpath of your site, e.g. /blog
url: "http://smmaguire.github.io" # the base hostname & protocol for your site
twitter_username: sm_maguire
github_username:  smmaguire

# Build settings
markdown: kramdown
